import Head from "next/head";
import Layout from "eos-lib/components/layout/layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Virtualized list</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout />
    </>
  );
}
