import Head from "next/head";
import { Inter } from "next/font/google";
import { ProductList } from "eos-lib/components/product-list/product-list";
import styles from "eos-lib/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Virtualized list</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <ProductList />
      </main>
    </>
  );
}
